---
- name: "Get current Roles from the Hub API"
  ansible.builtin.set_fact:
    hub_roles_lookvar: "{{ query('ansible.platform.gateway_api', '/api/galaxy/pulp/api/v3/roles/',
                                 query_params=({'name': hub_role_name} if hub_role_name is defined else {}),
                                 host=aap_hostname, oauth_token=aap_oauthtoken, verify_ssl=aap_validate_certs,
                                 return_all=true, max_objects=query_hub_api_max_objects)
                        }}"
  no_log: "{{ hub_configuration_filetree_create_secure_logging }}"

- name: "Create the output directory for hub roles: {{ output_path }}"
  ansible.builtin.file:
    path: "{{ output_path }}"
    state: directory
    mode: '0755'

- name: "Add current hub roles to the hub_roles.yaml output file in {{ output_path }}"
  ansible.builtin.template:
    src: "templates/hub_roles.j2"
    dest: "{{ output_path }}/hub_roles.yaml"
    mode: '0644'
  vars:
    current_hub_roles_asset_value: "{{ hub_roles_lookvar }}"
...
