---
- name: "Get current EE Registries from the Hub API"
  ansible.builtin.set_fact:
    hub_ee_registries_lookvar: "{{ (query('ansible.platform.gateway_api', '/api/galaxy/_ui/v1/execution-environments/registries/',
                                          query_params=({'name': hub_ee_registry_name} if hub_ee_registry_name is defined else {}
                                                        | combine({'url': hub_ee_url_namespace}) if hub_ee_url_namespace is defined else {}),
                                          host=aap_hostname, oauth_token=aap_oauthtoken, verify_ssl=aap_validate_certs,
                                          return_all=true, max_objects=query_hub_api_max_objects) | first).data
                             }}"
  no_log: "{{ hub_configuration_filetree_create_secure_logging }}"

- name: "Create the output directory for hub ee_registries: {{ output_path }}"
  ansible.builtin.file:
    path: "{{ output_path }}"
    state: directory
    mode: '0755'

- name: "Add current hub ee_registries to the hub_ee_registries.yaml output file in {{ output_path }}"
  ansible.builtin.template:
    src: "templates/hub_ee_registries.j2"
    dest: "{{ output_path }}/hub_ee_registries.yaml"
    mode: '0644'
  vars:
    current_hub_ee_registries_asset_value: "{{ hub_ee_registries_lookvar }}"
...
