---
- name: "Include tasks to check if user is a superuser"
  ansible.builtin.include_tasks:
    file: 'superuser_check.yml'

- name: "Instance Group differences (block)"
  when:
    - __controller_api_current_user_check_is_admin.is_superuser
  block:
    - name: "Get the API list of all instance_groups"
      ansible.builtin.set_fact:
        __controller_api_instance_groups: "{{ query('ansible.platform.gateway_api', 'api/controller/' + controller_api_version + '/instance_groups',
                                                    host=aap_hostname, oauth_token=aap_oauthtoken, verify_ssl=aap_validate_certs,
                                                    return_all=true, max_objects=query_controller_api_max_objects)
                                           }}"

    - name: "Find the difference of Instance Groups between what is on the Controller versus CasC on SCM"
      ansible.builtin.set_fact:
        __instance_groups_difference: "{{ query('infra.aap_configuration_extended.controller_object_diff',
                                                api_list=__controller_api_instance_groups,
                                                compare_list=controller_instance_groups,
                                                with_present=include_present_state,
                                                set_absent=true) | flatten
                                       }}"

    - name: "Sets the difference of Instance Groups between what is on the Controller versus CasC on SCM"
      ansible.builtin.set_fact:
        controller_instance_groups: "{{ __instance_groups_difference }}"
...
