---
- name: "Get the current controller user to determine if the user is a super-admin"
  ansible.builtin.set_fact:
    __controller_api_current_user_check_is_admin: >-
      {{
        lookup(
          'ansible.platform.gateway_api',
          'api/gateway/' ~ gateway_api_version ~ '/me',
          host=aap_hostname,
          oauth_token=aap_oauthtoken,
          verify_ssl=aap_validate_certs
        )
      }}
  no_log: "{{ controller_configuration_object_diff_secure_logging }}"
...
