---
# defaults file for object_diff

# populate_controller_api_user_accounts_without_external_accounts
drop_user_external_accounts: false
query_controller_api_max_objects: 10000

# Automation Controller Object Lists
controller_settings: []
aap_organizations: []
controller_labels: []
aap_user_accounts: []
aap_teams: []
controller_credential_types: []
controller_credentials: []
controller_credential_input_sources: []
controller_notifications: []
controller_projects: []
controller_execution_environments: []
aap_applications: []
controller_inventories: []
controller_inventory_sources: []
controller_instance_groups: []
controller_hosts: []
controller_groups: []
controller_templates: []
controller_workflows: []
controller_schedules: []
controller_roles: []

# object_diff tasks name
controller_configuration_object_diff_tasks:
  - {name: controller_schedules, var: controller_schedules, tags: controller_schedules}
  - {name: controller_workflow_job_templates, var: controller_workflows, tags: controller_workflow_job_templates}
  - {name: controller_job_templates, var: controller_templates, tags: controller_job_templates}
  - {name: controller_roles, var: controller_roles, tags: controller_roles}
  - {name: controller_teams, var: aap_teams, tags: controller_teams}
  - {name: controller_user_accounts, var: aap_user_accounts, tags: controller_users}
  - {name: controller_host_groups, var: controller_groups, tags: controller_host_groups}
  - {name: controller_hosts, var: controller_hosts, tags: controller_hosts}
  - {name: controller_applications, var: aap_applications, tags: controller_applications}
  - {name: controller_execution_environments, var: controller_execution_environments, tags: controller_execution_environments}
  - {name: controller_inventory_sources, var: controller_inventory_sources, tags: controller_inventory_sources}
  - {name: controller_inventories, var: controller_inventories, tags: controller_inventories}
  - {name: controller_projects, var: controller_projects, tags: controller_projects}
  - {name: controller_notification_templates, var: controller_notification_templates, tags: controller_notification_templates}
  - {name: controller_credentials, var: controller_credentials, tags: controller_credentials}
  - {name: controller_credential_types, var: controller_credential_types, tags: controller_credential_types}
  - {name: controller_organizations, var: aap_organizations, tags: controller_organizations}
  - {name: controller_instance_groups, var: controller_instance_groups, tags: controller_instance_groups}

controller_configuration_object_diff_secure_logging: "{{ controller_configuration_secure_logging | default(true) }}"

controller_api_version: "v2"
gateway_api_version: "v1"

include_present_state: false
...
