---
argument_specs:
  main:
    short_description: An Ansible Role to offline sync collections in Automation Hub.
    options:
      hub_configuration_working_dir:
        default: /var/tmp/hub_offline_sync
        type: str
        required: false
        description: The working directory where the collections will be downloaded and any required files.
      hub_configuration_no_deps:
        default: false
        type: bool
        required: false
        description: Whether to download all dependencies for each collection or not, if false it may cause errors if dependency sync is off in Automation Hub.

      # Generic across all roles
      aap_hostname:
        required: false
        description: URL to the Ansible Automation Platform Server.
        type: str
        default: "{{ hub_host }}"
      hub_path_prefix:
        required: false
        description: The path for the Automation Hub API. Usually galaxy or automation-hub unless custom set in AH settings.
      aap_validate_certs:
        required: false
        description: Whether or not to validate the Automation Hub Server's SSL certificate.
        type: str
      aap_request_timeout:
        default: 10
        required: false
        description: Specify the timeout Ansible should use in requests to the Galaxy or Automation Hub host.
        type: float
      aap_username:
        required: false
        description: User for authentication on Automation Hub
        type: str
      aap_password:
        required: false
        description: User's password For Automation Hub
        type: str
      aap_token:
        required: false
        description: User's token on the Automation Hub Server
        type: str
...
